In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('./data/words.tsv', sep='\t')

df.head()

       word  length
0    indeed       6
1  possible       8
2        my       2

Row

In [4]:
df = df.drop(1, axis=0)

df.head()

     word  length
0  indeed       6
2      my       2

Column

In [6]:
df = df.drop('length', axis=1)

df.head()

     word
0  indeed
2      my