In [1]:
import pandas as pd
from faker import Faker

In [2]:
fake = Faker()
words = fake.words(nb=5)

In [3]:
df = pd.DataFrame({ 'word': words, 'length': [len(word) for word in words] })

df.head()

     word  length
0   space       5
1   allow       5
2     set       3
3   owner       5
4  itself       6

---

### Exploration

In [4]:
df.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   word    5 non-null      str
 1   length  5 non-null      int64
dtypes: int64(1), str(1)
memory usage: 236.0 bytes

In [5]:
df.describe(percentiles=None, include='all')

         word    length
count       5  5.000000
unique      5       NaN
top     space       NaN
freq        1       NaN
mean      NaN  4.800000
std       NaN  1.095445
min       NaN  3.000000
25%       NaN  5.000000
50%       NaN  5.000000
75%       NaN  5.000000
max       NaN  6.000000

In [6]:
df.shape

(5, 2)

In [7]:
df.value_counts(subset='length')

length
5    3
3    1
6    1
Name: count, dtype: int64

### Rows

In [8]:
df.loc[0:2]

    word  length
0  space       5
1  allow       5
2    set       3

In [9]:
df.iloc[0:2]

    word  length
0  space       5
1  allow       5

In [ ]:
df.word[0], df['word'][0] # attribute and item access are equivalent

indexes

In [10]:
df.index.tolist()

[0, 1, 2, 3, 4]

### Columns

In [13]:
df['word']

0     space
1     allow
2       set
3     owner
4    itself
Name: word, dtype: str

In [14]:
df.word

0     space
1     allow
2       set
3     owner
4    itself
Name: word, dtype: str

In [12]:
df.columns.tolist()

['word', 'length']

In [11]:
df.columns.dtype

In [15]:
df[['word', 'length']].head()

     word  length
0   space       5
1   allow       5
2     set       3
3   owner       5
4  itself       6

In [16]:
df.loc[:, ['word', 'length']].head() # Label based index

     word  length
0   space       5
1   allow       5
2     set       3
3   owner       5
4  itself       6

In [17]:
df.iloc[:, [0, 1]].head() # Index based

     word  length
0   space       5
1   allow       5
2     set       3
3   owner       5
4  itself       6

### Values

In [18]:
df['word'].values.tolist()

['space', 'allow', 'set', 'owner', 'itself']

In [19]:
df[['word', 'length']].values.tolist()

[['space', 5], ['allow', 5], ['set', 3], ['owner', 5], ['itself', 6]]

In [20]:
df.values.tolist()

[['space', 5], ['allow', 5], ['set', 3], ['owner', 5], ['itself', 6]]

### Filter

In [21]:
df[df['length'] < 5].head()

  word  length
2  set       3

##### Callback

In [22]:
def create_filter(column, threshold):
    def _filter(dataframe):
        return dataframe[column] < threshold
    return _filter

In [23]:
cb = create_filter('length', 5)
df[cb].head()

  word  length
2  set       3