In [1]:
import pandas as pd
from faker import Faker
import numpy as np

In [2]:
fake = Faker()

---

### Series

##### like columns

In [17]:
pd.Series(fake.words()).head()

0      site
1    friend
2    during
dtype: str

In [26]:
numbers = np.array([i for i in range(3)])
numbers

array([0, 1, 2])

In [18]:
pd.Series(numbers, index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A').head()

site      0
friend    1
during    2
Name: Title, dtype: int64

### DataFrame

###### like whole table

In [29]:
words = fake.words()
words

['second', 'think', 'point']

In [21]:
pd.DataFrame(words, columns=['word']).head()

     word
0    site
1  friend
2  during

In [22]:
pd.Series(words).to_frame(name='word').head()

     word
0    site
1  friend
2  during

In [25]:
word_and_length = { 'word': words, 'length': [len(word) for word in words] }
word_and_length

{'word': ['site', 'friend', 'during'], 'length': [4, 6, 6]}

In [30]:
pd.DataFrame(word_and_length).head()

     word  length
0    site       4
1  friend       6
2  during       6

In [31]:
word_and_length_items = {word: len(word) for word in words}.items()
word_and_length_items

dict_items([('second', 6), ('think', 5), ('point', 5)])

In [32]:
pd.DataFrame(word_and_length_items, index=range(len(words)), columns=['word', 'length']).head()

     word  length
0  second       6
1   think       5
2   point       5

### Copy

In [9]:
df[['word']].copy().head()

NameError: name 'df' is not defined

In [ ]:
df['word'].copy().head()