In [37]:
import pandas as pd
import numpy as np
from faker import Faker

In [27]:
fake = Faker()
records_count = 10

In [28]:
sexes = list(map(lambda _: 'M' if fake.boolean() else 'F', [*range(records_count)]))

df = pd.DataFrame({
    'name': list(map(lambda sex: fake.first_name_male() if sex == 'M' else fake.first_name_female(), sexes)),
    'sex': sexes,
    'children': list(map(lambda _: fake.random_digit(), [0] * records_count)),
    'income': list(map(lambda _: fake.random_int(min= 3000, max= 10000), [*range(records_count)])),
})

df.head()

       name sex  children  income
0  Jennifer   F         3    8448
1    Edward   M         6    4543
2     Jason   M         2    8306
3    Amanda   F         3    3868
4     Duane   M         8    7549

In [29]:
df.describe(percentiles=None, include='all')

          name  sex   children       income
count       10   10  10.000000    10.000000
unique       9    2        NaN          NaN
top     Edward    M        NaN          NaN
freq         2    8        NaN          NaN
mean       NaN  NaN   3.800000  6769.700000
std        NaN  NaN   2.299758  1924.766713
min        NaN  NaN   1.000000  3868.000000
25%        NaN  NaN   2.000000  4873.500000
50%        NaN  NaN   3.000000  7489.000000
75%        NaN  NaN   5.750000  8383.250000
max        NaN  NaN   8.000000  8899.000000

### Mean

In [30]:
df[['children']].mean()

children    3.8
dtype: float64

### Median

In [31]:
df[['income']].median()

income    7489.0
dtype: float64

### Mode

In [32]:
df[['sex']].mode()

  sex
0   M

### Variance

In [43]:
# Series and DataFrame normalizes by N-1 (unbiased variance), while numpy.var normalizes by N (biased variance)

df[['income']].mean(), df[['income']].var(), df['income'].var(), np.var(df['income'])

(income    6769.7
 dtype: float64,
 income    3704726.9
 dtype: float64,
 3704726.9000000004,
 3334254.21)

### Standard deviation

In [36]:
df[['income']].mean(), df[['income']].std()

(income    6769.7
 dtype: float64,
 income    1924.766713
 dtype: float64)