In [2]:
import pandas as pd

---

In [3]:
df = pd.read_csv('./data/words.tsv', sep='\t')

df.head()

       word  length
0    indeed       6
1  possible       8
2        my       2

---

Row

In [4]:
# new
df.loc[len(df.index)] = {'word': 'test', 'length': 4}
# update
df.loc[1, ['word']] = 'updated_word'
df.loc[2, ['word', 'length']] = ['one', 2]

df.head()

           word  length
0        indeed       6
1  updated_word       8
2           one       2
3          test       4

Column

In [7]:
df['type'] = ['aux', 'updated', 'number', 'test']

df.head()

           word  length         UPPER     type
0        indeed       6        INDEED      aux
1  updated_word       8  UPDATED_WORD  updated
2           one       2           ONE   number
3          test       4          TEST     test

In [8]:
df[['is_known', 'is_in_study']] = [[1, 0], [1, 0], [1, 0], [1, 0]]

df.head()

           word  length         UPPER     type  is_known  is_in_study
0        indeed       6        INDEED      aux         1            0
1  updated_word       8  UPDATED_WORD  updated         1            0
2           one       2           ONE   number         1            0
3          test       4          TEST     test         1            0

Entire

CrossTab

In [10]:
data = {
    "Gender": ["M", "M", "F", "F", "M", "F", "M"],
    "AgeGroup": ["18-30", "18-30", "18-30", "31-50", "31-50", "31-50", "18-30"],
    "Purchased": [1, 0, 1, 1, 0, 1, 1],
}

In [11]:
cross_tab_df = pd.DataFrame(data)

In [12]:
cross_tab = pd.crosstab(index=cross_tab_df["Gender"], columns=cross_tab_df["AgeGroup"], values=cross_tab_df["Purchased"], aggfunc="sum")

In [13]:
print(cross_tab)

AgeGroup  18-30  31-50
Gender
F             1      2
M             2      0